<a href="[field:typelink /]" target="_blank">
    [field:typename /]
</a>
<ul class="ul-box">
    {dede:list row="2" pagesize="2" titlelen="46"}
    <li>
        <span>[field:global.autoindex/]</span>
        <a href="[field:arcurl/]">
            <p>[field:title/]</p>
        </a>
    </li>
    {/dede:list}
</ul>
<div id="pageNav">
    <ul>{dede:pagelist listitem="info,pre,next,pageno" listsize="2"/}</ul>
</div>