<?php
$z[0]=Array("field","",68,96);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",114,143);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                                    <li>\r\n                                        <a href=\"[field:arcurl /]\" target=\"_blank\">\r\n                                            [field:title /]\r\n                                        </a>\r\n                                    </li>\r\n                                ",246,609);
$z[2][4]['titlelen']="42";
$z[2][4]['row']="20";

?>