<div class="hot-art clearfix">
                                        <div class="clearfix">
                                            <div class="hot fl">
                                                <img src="[field:litpic/]" style="border: none" alt="[field:title /]">
                                            </div>
                                            <div class="arti">
                                                <h3>[field:title /]</h3>
                                                <p>[field:description function="cn_substr(@me,120)"/]... <span><a href="[field:arcurl /]" target="_blank">[ฯ๊ว้]</a></span>
                                                </p>
                                            </div>
                                        </div>
                                    </div>