<div class="fl">
                            <img src="[field:litpic/]" style="border: none" alt="[field:title /]">
                        </div>
                        <div class="fr">
                            <h3>[field:title/]</h3>
                            <p>[field:description function="cn_substr(@me,120)"/]...
                                <a href="[field:arcurl /]" target="_blank">[ฯ๊ว้]</a>
                            </p>
                        </div>