<?php
$z[0]=Array("field","",127,156);
$z[0][4]['name']="typename";
$z[1]=Array("field","",221,249);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n                                <div class=\"clearfix li\">\r\n                                    <div class=\"pic fl\">\r\n                                        <img src=\"[field:litpic/]\" style=\"border: none\" alt=\"[field:title /]\">\r\n                                    </div>\r\n                                    <div class=\"ul-box1-article fl\">\r\n                                        <h3>[field:title /]</h3>\r\n                                        <p>[field:description function=\"cn_substr(@me,120)\"/]... <span><a href=\"[field:arcurl /]\" target=\"_blank\">【查看更多】</a></span></p>\r\n                                    </div>\r\n                                </div>\r\n                                ",457,1239);
$z[2][4]['pagesize']="1";
$z[2][4]['flag']="a";
$z[2][4]['titlelen']="46";
$z[2][4]['orderby']="rand";
$z[3]=Array("arclist","\r\n                                        <li>\r\n                                            <a href=\"[field:arcurl /] \" target=\"_blank\">\r\n                                                [field:title /]\r\n                                            </a>\r\n                                        </li>\r\n                                        ",1407,1829);
$z[3][4]['pagesize']="8";
$z[3][4]['noflag']="a";
$z[3][4]['titlelen']="46";
$z[3][4]['orderby']="rand";

?>