<?php
$z[0]=Array("field","",59,88);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n                                    <li>\r\n                                        <a href=\"[field:arcurl /]\" target=\"_blank\">\r\n                                            [field:title /]\r\n                                        </a>\r\n                                    </li>\r\n                                ",187,550);
$z[1][4]['titlelen']="42";
$z[1][4]['row']="20";

?>