<?php
$z[0]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",647,749);
$z[0][4]['typeid']="31";
$z[1]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",785,887);
$z[1][4]['typeid']="32";
$z[2]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",923,1025);
$z[2][4]['typeid']="33";
$z[3]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",1061,1163);
$z[3][4]['typeid']="34";
$z[4]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",1199,1301);
$z[4][4]['typeid']="38";
$z[5]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",1337,1439);
$z[5][4]['typeid']="35";
$z[6]=Array("type","<a  href='[field:typelink /]'target=\"_blank\">[field:typename /]</a>",1475,1577);
$z[6][4]['typeid']="36";

?>