<?php
$z[0]=Array("field","",32,60);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",62,91);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n        <ul class='autod'>\r\n            <li>\r\n                ндуб╠ЙлБ: <a href=\"[field:arcurl /]\">\r\n                [field:title /]\r\n            </a>\r\n            </li>\r\n        </ul>\r\n        ",120,368);
$z[2][4]['titlelen']="42";
$z[2][4]['row']="20";

?>