<?php
$z[0]=Array("arclist","\r\n                                    <div class=\"hot-art clearfix\">\r\n                                        <div class=\"clearfix\">\r\n                                            <div class=\"hot fl\">\r\n                                                <img src=\"[field:litpic/]\" style=\"border: none\" alt=\"[field:title /]\">\r\n                                            </div>\r\n                                            <div class=\"arti\">\r\n                                                <h3>[field:title /]</h3>\r\n                                                <p>[field:description function=\"cn_substr(@me,120)\"/]... <span><a href=\"[field:arcurl /]\" target=\"_blank\">[ฯ๊ว้]</a></span>\r\n                                                </p>\r\n                                            </div>\r\n                                        </div>\r\n                                    </div>\r\n                                    ",42,1039);
$z[0][4]['row']="1";
$z[0][4]['flag']="h,p";
$z[0][4]['titlelen']="46";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("arclist","\r\n                                            <li>\r\n                                                <a href=\"[field:arcurl /] \" target=\"_blank\">\r\n                                                    [field:title /]\r\n                                                    <ins>\r\n                                                        <script src=\"/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]\" type='text/javascript' language=\"javascript\"></script>\r\n                                                    </ins>\r\n                                                </a>\r\n                                            </li>\r\n                                            ",1212,1959);
$z[1][4]['row']="6";
$z[1][4]['noflag']="h";
$z[1][4]['titlelen']="46";
$z[1][4]['orderby']="pubdate";

?>