<?php
$z[0]=Array("field","",21,49);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",51,80);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n<h3>二级标题:<a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a></h3>\r\n{dede:arclist row='5' titlelen='39'}\r\n<p>文章标题： <a href=\"{field:arcurl/}\" target=\"_blank\">{field:title/}</a></p>\r\n{/dede:arclist}\r\n",90,362);
$z[2][4]['type']="sun";
$z[2][4]['sanji']="1";

?>