<li>
                                                <a href="[field:arcurl /] " target="_blank">
                                                    [field:title /]
                                                    <ins>
                                                        <script src="/plus/count.php?view=yes&aid=[field:id/]&mid=[field:mid/]" type='text/javascript' language="javascript"></script>
                                                    </ins>
                                                </a>
                                            </li>