<?php
$z[0]=Array("field","",283,306);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",307,333);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",381,411);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",452,479);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2247,2441);
$z[4][4]['typeid']="31";
$z[5]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2517,2711);
$z[5][4]['typeid']="32";
$z[6]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2787,2981);
$z[6][4]['typeid']="33";
$z[7]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",3057,3251);
$z[7][4]['typeid']="34";
$z[8]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",3327,3521);
$z[8][4]['typeid']="38";
$z[9]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",3579,3773);
$z[9][4]['typeid']="35";
$z[10]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",3849,4043);
$z[10][4]['typeid']="36";
$z[11]=Array("field","",4704,4733);
$z[11][4]['name']="position";
$z[12]=Array("arclist","\r\n                <a href='[field:arcurl/]' target=\"_blank\">[field:title/] |</a>\r\n                ",4891,5079);
$z[12][4]['row']="3";
$z[12][4]['flag']="s";
$z[12][4]['orderby']="rand";
$z[12][4]['titlelen']="46";
$z[12][4]['typeid']="rand";
$z[13]=Array("field","",21358,21387);
$z[13][4]['name']="typename";
$z[14]=Array("channelartlist","\r\n                        <li class=\"projects-box\">\r\n                            <h3><a href=\"{dede:field name='typeurl'/}\" target=\"_blank\">{dede:field name='typename'/}</a></h3>\r\n                            <ul class=\"projects clearfix\">\r\n                                {dede:arclist titlelen='42' row='20'}\r\n                                    <li>\r\n                                        <a href=\"[field:arcurl /]\" target=\"_blank\">\r\n                                            [field:title /]\r\n                                        </a>\r\n                                    </li>\r\n                                {/dede:arclist}\r\n                            </ul>\r\n                        </li>\r\n                        ",21729,22508);
$z[14][4]['row']="20";
$z[15]=Array("type","\r\n                            <span><a href=\"[field:typelink /]\" target=\"_blank\">¡¾ÏêÇé¡¿</a></span>\r\n                            ",22931,23096);
$z[15][4]['typeid']="31";

?>