<?php
$z[0]=Array("global","",341,371);
$z[0][4]['name']="cfg_description";
$z[1]=Array("global","",412,439);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2082,2276);
$z[2][4]['typeid']="31";
$z[3]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2352,2546);
$z[3][4]['typeid']="32";
$z[4]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2622,2816);
$z[4][4]['typeid']="33";
$z[5]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",2892,3086);
$z[5][4]['typeid']="34";
$z[6]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",3238,3432);
$z[6][4]['typeid']="35";
$z[7]=Array("type","\r\n                    <a href='[field:typelink /]' target=\"_blank\">\r\n                        [field:typename /]\r\n                    </a>\r\n                    ",3508,3702);
$z[7][4]['typeid']="36";
$z[8]=Array("field","",4363,4392);
$z[8][4]['name']="position";
$z[9]=Array("arclist","\r\n                <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                    [field:title /] |\r\n                </a>\r\n                ",4550,4770);
$z[9][4]['titlelen']="46";
$z[9][4]['orderby']="rand";
$z[9][4]['flag']="s";
$z[9][4]['pagesize']="3";
$z[10]=Array("field","",5308,5337);
$z[10][4]['name']="typename";
$z[11]=Array("list","\r\n                        <li>\r\n                            <span>[field:global.autoindex/]</span>\r\n                            <a href=\"[field:arcurl/]\">\r\n                                <p>[field:title/]</p>\r\n                            </a>\r\n                        </li>\r\n                        ",5674,6034);
$z[11][4]['row']="15";
$z[11][4]['pagesize']="15";
$z[11][4]['titlelen']="46";
$z[12]=Array("pagelist","",6137,6208);
$z[12][4]['listitem']="index,pageno,info,pre,next,end";
$z[12][4]['listsize']="2";
$z[13]=Array("type","\r\n                            <span><a href=\"[field:typelink /]\" target=\"_blank\">¡¾ÏêÇé¡¿</a></span>\r\n                            ",6639,6804);
$z[13][4]['typeid']="31";

?>